# Generated by Django 5.0.7 on 2024-08-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_projectrequrment'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='submit_reqirment',
            field=models.BooleanField(default=False),
        ),
    ]
