# Generated by Django 5.0.7 on 2024-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_proposal_submit_reqirment'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reveiw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='submit_project',
            field=models.BooleanField(default=False),
        ),
    ]
