# Generated by Django 5.0.7 on 2024-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('between', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer'), ('admin', 'admin')], max_length=50),
        ),
    ]
