# Generated by Django 5.0.7 on 2024-08-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='category',
            field=models.ManyToManyField(to='buyer.addcategory'),
        ),
    ]
